-- 코드를 입력하세요
SELECT MEMBER_ID, MEMBER_NAME, GENDER, TO_CHAR(DATE_OF_BIRTH, 'yyyy-mm-dd') DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE TLNO IS NOT NULL
AND TO_CHAR(DATE_OF_BIRTH, 'mm') = 3
AND gender = 'W'
ORDER BY MEMBER_ID ASC;